language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
  
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: false
